### ISSUE TITLE
[issue] Divergents do not tending any plants while mod BetterFarmingEffects is active

### ISSUE THREAD

**Issue by YAAkimov** [SanchozzDeponianin/ONIMods#27]
## Expected Behavior
Sweetle and grubgrubs not tending any plants while mod BetterFarmingEffects is active
Spaced Out installed

## Current Behavior
Nothing. Over 30 cycles no one divergent tended any plant.

## Mod Versions
Steam Subscription
Tried force update, nothing happens

## Steps to Reproduce
1. Install mod
2. Ranch a Divergent
3. And see, that no one sweetle has no tending plants

## Game Log
[Player-prev.log](https://github.com/SanchozzDeponianin/ONIMods/files/9846624/Player-prev.log)

**Comment by coilysiren** [comment]
Here is an additional player log for this issue: https://pastebin.com/RradEGwQ

**Comment by SanchozzDeponianin** [comment]
Thanks for the report. However, I already found the cause of the problem a few hours ago.
The problem was caused by undefined behavior in a piece of code written more than a year and a half ago, which, due to changes in the game itself, unexpectedly did not cause a crash (as it usually happens every time the game is updated), but continued to work at first glance as expected. Divergents tended plants, but only on the first asteroid (where the portal and the first duplicants will spawn at the start of a new game). Therefore, the problem was not noticed during testing.
fixed at d6a90230e3062db7278df557585c35447d7bfea1
