### ISSUE TITLE
Eat Every Day? question?

### ISSUE THREAD

**Issue by Mementh** [SanchozzDeponianin/ONIMods#30]
howdy, I don't play on no stress and wondering if eat every day already covers the regular game? or if it could be setup to do so, i get alot of starving notifications and its annoying when they would just eat at the end of a day!

**Comment by SanchozzDeponianin** [comment]
HI
in a regular game, duplicants will already eat at least 1 time per cycle, even without this mod.

so I didn't understand the question.

do you play on increased difficulty ?

your duplicants get hungry in a cycle - enough for the starving notification to appear ?

and do you want a new feature so that they go to eat before the starving notification appears, regardless of the schedule, even several times a day ?

**Comment by Mementh** [comment]
So most eat on "downtime" but alot will not eat to full? So they eventually get to 900 callories left 
It happens often, with 13 dupes i usually get 1 every few days?

And its normal difficulty. 

Usually they will go to the bathroom, then eat, then go to sleep.
But at times i think the use bathroom takes longer or they started late, so they skip meals because they are not starving and go to bed.

**Comment by SanchozzDeponianin** [comment]
apparently, you have allocated too little "downtime" time. just give your duplicants more "downtime" time. 
and the mod has absolutely nothing to do with it.
