### ISSUE TITLE
Fishing Station doesn't seem to work in public version 551176 (Whatta Blast)[issue]

### ISSUE THREAD

**Issue by InTheComfyChair** [SanchozzDeponianin/ONIMods#37]
Using the March 27th version of the Butcher/Fishing station mod with v551176 of ONI results in dupes standing at the fishing station and whistling forever, with no fish ever coming to the hook to be wrangled.

Previously, the same fishing stations in the same locations worked fine for hundreds of cycles. Butcher stations seem to work fine.

Love your mods!

**Comment by SanchozzDeponianin** [comment]
A quick test showed that the problem is observed when there are different rooms at the top and bottom of the station.
And everything works well when the same room is at the top and bottom.
![457140_20230401180536_1](https://user-images.githubusercontent.com/73459473/229289173-b74603fb-604f-4be6-b3de-229706e30d9e.png)
![457140_20230401180624_1](https://user-images.githubusercontent.com/73459473/229289180-782709be-4822-482d-ae6e-10978edf67e6.png)
Also, the problem is not observed in the previous version of the game U45.
Presumably it is associated with the change of March 28
> Fixed an issue where critters would sometimes freeze if a Duplicant tried to use their previous Grooming Station when there were no other eligible critters inside that room.

I'll see what's broken there.

**Comment by InTheComfyChair** [comment]
Ah, I see. So my dupes get to do some hopping over a hole for a while. :)

Now I get to watch one rancher try to catch about 100 fish! 👍

**Comment by SanchozzDeponianin** [comment]
I uploaded a new version of the mod to steam and to [github](https://github.com/SanchozzDeponianin/ONIMods/releases/latest)
