### ISSUE TITLE
[Butcher & Fishing Stations] Feature Request: configurable size of butcher station

### ISSUE THREAD

**Issue by tsunamilx** [SanchozzDeponianin/ONIMods#50]
### Description of the bug/crash

Title
From the visual the butcher station looks like the size of 2x2, the first time I used this mod and got confused why I can't place the building, turns out it is 3x3 size.
I always want to build something compact, this actually bothers me a lot.
Much appreciated if you can change the size to 2x2 or 2x3; or better, make it configurable; or at least tell me where I can modify the source code so I can make a local mod, I have little experience about modding, but I'll give a try if necessary.
Thanks.

### Steps To Reproduce

--

### Player.log

--

**Comment by SanchozzDeponianin** [comment]
Hi.
Actually, this station visually looks 2x3, not 2x2. But I had several good reasons to make it 3x3

First, the mod reuses existing animations of duplicants and animals. Because creating new animations is an extremely time-consuming and thankless process. In particular, the duplicant animation from the Shearing station is used. And it is designed for a building with a width of 3. If I make a Butcher station with a width of 2, something strange may turn out, for example, a duplicant will be drawn inside the wall.
![2023-10-07 13-58-52](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/547ea7e7-aba2-4602-a9c5-076b7b20d2e6)

Secondly, I wanted the animal to be positioned in the center of the building, and not sideways to the left or right, for this the width should be an odd number.

And thirdly. I really don't want to provide end users with the ability to configure the size of buildings. This can lead to extremely strange consequences. For example, if a user builds 2x3 buildings, saves, then changes the configuration to 3x3, and loads his save file - neighboring buildings will overlap with each other.

**Comment by tsunamilx** [comment]
Thanks a lot for taking the time to write the details. You've made good point, and I will close the issue myself.
