### ISSUE TITLE
Is any update needed for frosty planet DLC?[Issue]: 

### ISSUE THREAD

**Issue by mooklepticon** [SanchozzDeponianin/ONIMods#71]
### Description of the bug/crash

asdf

### Steps To Reproduce

asdf

### Player.log

asdf

**Comment by SanchozzDeponianin** [comment]
Clarify the question please. Nothing is clear.

**Comment by mooklepticon** [comment]
Oxygen Not Included mods. There is a new DLC, The Frosty Planet Pack. Along
with it, there was a game update. Are any updates needed to your mods?

**Comment by jordanmyte** [comment]
Because of the dlc update, any mods using Plib Options would cause a game launch crash due to a dlc check going bad. Since there isnt any steam comments allowed on the mods there is no fast way to see if there was an issue with a specific mod. So we are here to see if you noticed any issues with your mods. (please allow comments on steam)

**Comment by jordanmyte** [comment]
You didnt answer the question...
